on: push
name: npm build, lint, test and publish
jobs:
  build-and-publish:
    name: build and publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: npm install
        uses: actions/npm@master
        with:
          args: install
      - name: npm lint
        uses: actions/npm@master
        with:
          args: run lint
      - name: npm test
        uses: actions/npm@master
        with:
          args: run test
      - name: docker build
        uses: actions/docker/cli@master
        with:
          args: build --build-arg PORT=3000 --tag agmdev/sazed-api:latest .
      - name: docker login
        uses: actions/docker/login@master
        env:
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      - name: docker push
        uses: actions/docker/cli@master
        with:
          args: push agmdev/sazed-api
